package com.tianranmei.po;
// Generated 2016-4-19 10:01:46 by Hibernate Tools 4.3.1.Final

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	private Integer id;
	private String kahao;
	private String password;
	private String phone;
	private String name;
	private String sex;
	private Integer age;
	private String interest;
	private Integer zodiacId;
	private String des;

	public Member() {
	}

	public Member(String kahao, String password, String phone, String name, String sex, Integer age, String interest,
			Integer zodiacId, String des) {
		this.kahao = kahao;
		this.password = password;
		this.phone = phone;
		this.name = name;
		this.sex = sex;
		this.age = age;
		this.interest = interest;
		this.zodiacId = zodiacId;
		this.des = des;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKahao() {
		return this.kahao;
	}

	public void setKahao(String kahao) {
		this.kahao = kahao;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getInterest() {
		return this.interest;
	}

	public void setInterest(String interest) {
		this.interest = interest;
	}

	public Integer getZodiacId() {
		return this.zodiacId;
	}

	public void setZodiacId(Integer zodiacId) {
		this.zodiacId = zodiacId;
	}

	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

}
