package com.tianranmei.po;
// Generated 2016-4-21 16:21:23 by Hibernate Tools 4.3.1.Final

/**
 * Zodiak generated by hbm2java
 */
public class Zodiak implements java.io.Serializable {

	private Integer id;
	private String code;
	private String name;
	private byte type;

	public Zodiak() {
	}

	public Zodiak(String code, String name, byte type) {
		this.code = code;
		this.name = name;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte getType() {
		return this.type;
	}

	public void setType(byte type) {
		this.type = type;
	}

}
